#%RAML 1.0 NamedExample
value:
  -
    CommentId: 1
    HaikuId : 1234
    NickName: "UserA"
    Comment: "コメント1"
    CreateDate: 2016-02-28T17:41:41.090Z
  -
    CommentId: 2
    HaikuId : 1234
    NickName: "UserB"
    Comment: "コメント2"
    CreateDate: 2016-02-28T18:41:41.090Z
  -
    CommentId: 2
    HaikuId : 1234
    NickName: "UserC"
    Comment: "コメント3"
    CreateDate: 2016-02-28T19:41:41.090Z
